CUSTOM_MATRIX = yes

# project specific files
SRC = matrix.c

DEFAULT_FOLDER = hhkb/ansi/32u4

AVR_USE_MINIMAL_PRINTF = yes
BOOTLOADER = atmel-dfu
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DEBOUNCE_TYPE = asym_eager_defer_pk
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
NO_USB_STARTUP_CHECK = yes
RING_BUFFERED_6KRO_REPORT_ENABLE = yes
SPACE_CADET_ENABLE = no
TERMINAL_ENABLE = no
USB_WAIT_FOR_ENUMERATION = no

OPT_DEFS += "-w"
OPT_DEFS += "-Ofast"
OPT_DEFS += "-flto=16"
